-- MySQL Script generated by MySQL Workbench
-- Sat Dec 15 13:31:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_stone_mall
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_stone_mall` ;

-- -----------------------------------------------------
-- Schema db_stone_mall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_stone_mall` DEFAULT CHARACTER SET utf8 ;
USE `db_stone_mall` ;

-- -----------------------------------------------------
-- Table `db_stone_mall`.`tb_upms_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_stone_mall`.`tb_upms_user` ;

CREATE TABLE IF NOT EXISTS `db_stone_mall`.`tb_upms_user` (
  `userId` INT NOT NULL,
  `userName` VARCHAR(45) NULL,
  `pwd` VARCHAR(45) NULL,
  `realName` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `createTime` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_stone_mall`.`tb_upms_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_stone_mall`.`tb_upms_role` ;

CREATE TABLE IF NOT EXISTS `db_stone_mall`.`tb_upms_role` (
  `roleId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `createTime` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_stone_mall`.`tb_upms_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_stone_mall`.`tb_upms_user_role` ;

CREATE TABLE IF NOT EXISTS `db_stone_mall`.`tb_upms_user_role` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `roleId` INT NOT NULL,
  PRIMARY KEY (`id`, `userId`, `roleId`),
  INDEX `fk_tb_upms_user_role_tb_upms_user_idx` (`userId` ASC),
  INDEX `fk_tb_upms_user_role_tb_upms_role1_idx` (`roleId` ASC),
  CONSTRAINT `fk_tb_upms_user_role_tb_upms_user`
    FOREIGN KEY (`userId`)
    REFERENCES `db_stone_mall`.`tb_upms_user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_upms_user_role_tb_upms_role1`
    FOREIGN KEY (`roleId`)
    REFERENCES `db_stone_mall`.`tb_upms_role` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into tb_upms_user values(0,'cfq','test','','','');

insert into tb_upms_role values(0,'guest','','guest');
insert into tb_upms_role values(1,'admin','','admin');

insert into tb_upms_user_role values(0,0,1);
